# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1410086922);
user_pref("app.update.lastUpdateTime.background-update-timer", 1410086571);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1410087048);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1410080505);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1410086802);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1410086444);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140716183446");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 726);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20140716183446");
user_pref("browser.startup.homepage_override.mstone", "31.0");
user_pref("browser.uitour.whitelist.add.260", "");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1410166784945");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1410080384944");
user_pref("datareporting.sessions.current.activeTicks", 22);
user_pref("datareporting.sessions.current.firstPaint", 580);
user_pref("datareporting.sessions.current.main", 30);
user_pref("datareporting.sessions.current.sessionRestored", 649);
user_pref("datareporting.sessions.current.startTime", "1410086682019");
user_pref("datareporting.sessions.current.totalTime", 391);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.previous.0", "{\"s\":1410080384705,\"a\":16,\"t\":199,\"c\":true,\"m\":32,\"fp\":798,\"sr\":905}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1410086314271,\"a\":13,\"t\":365,\"c\":true,\"m\":27,\"fp\":589,\"sr\":658}");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:31.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20140527.01.3");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/Applications/Firefox.app/Contents/MacOS/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1405570358000,\"rdfTime\":1405565774000}}}]");
user_pref("extensions.lastAppVersion", "31.0");
user_pref("extensions.lastPlatformVersion", "31.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20140716183446");
user_pref("gecko.mstone", "31.0");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.cpd.cache", false);
user_pref("privacy.cpd.downloads", false);
user_pref("privacy.cpd.history", false);
user_pref("privacy.cpd.sessions", false);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("toolkit.startup.last_success", 1410086682);
user_pref("toolkit.telemetry.previousBuildID", "20140716183446");
